before_install: 
  - gem install racc -v 1.5.2
  - gem install mimemagic -v 0.3.8
  - bundle install
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
